name: Build GNU Toolchain

on:
  push:
    branches: [ v2004-toolchain-only-package ]
  pull_request:
    branches: [ v2004-toolchain-only-package ]

jobs:
  build_bare_linux_windows:
    name: baremetal for ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#         os: [ubuntu-latest]
        os: [ubuntu-16.04]
    env: 
      CC: gcc-8
      CXX: g++-8

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          sudo apt-get install cmake autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf patchutils bc zlib1g-dev libexpat-dev libtool pkg-config mingw-w64
    - name: Build Toolchain
      run: |
        make toolchain
